config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  resources :burgers
  resources :drinks
  resources :fries
  resources :articles
  resources :desserts

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/burger.rb
class Burger < Article

	validates_presence_of :name
	validates_numericality_of :price
	
end

app/models/dessert.rb
class Dessert < Article
end

app/models/drink.rb
class Drink < Article
end

app/models/fry.rb
class Fry < Article
	enum size: [:large, :medium, :small]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def new
	end

	def index
		@articles = Article.all
	end
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController

	def index
		@burgers = Burger.all
	end 

	def show
		@burger = Burger.find(params[:id])
	end

	def new
		@burger = Burger.new
	end

	def edit
		@burger = Burger.find(params[:id])
	end


	def create
		@burger = Burger.new(params.require(:burger).permit(:name,:price))
		if @burger.save
			redirect_to :burgers
		else
			render 'new'
		end
	end

	def destroy
		@burger = Burger.find(params[:id])
		@burger.destroy
		# render :action => :index
		redirect_to :burgers
	end


end

app/controllers/desserts_controller.rb
class DessertsController < ApplicationController

	def index
		@desserts = Dessert.all
	end

	def show
		@dessert = Dessert.find(params[:id])
	end

	def new
		@dessert = Dessert.new
	end

	def create
		@dessert = Dessert.new(params.require(:dessert).permit(:name,:price))
		if @dessert.save
			redirect_to @dessert
		else
			redirect_to :new_dessert
		end
	end

	def destroy
		@dessert = Dessert.find(params[:id])
		@dessert.destroy
		redirect_to :desserts
	end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

	def index
		@drinks = Drink.all
	end

	def show
		@drink = Drink.find(params[:id])
	end

	def new
		@drink = Drink.new
	end

	def create
		@drink = Drink.new(params.require(:drink).permit(:name, :quantity, :price, :unit))
		if @drink.save
			render :show
		else
			render :new
		end
	end

	def destroy
		@drink = Drink.find(params[:id])
		@drink.destroy
		redirect_to :drinks
	end
end

app/controllers/fries_controller.rb
class FriesController < ApplicationController

	def index
		@fries = Fry.all
	end

	def show
		@fry = Fry.find(params[:id])
	end

	def new
		@fry = Fry.new
	end

	def create
		@fry = Fry.new(params.require(:fry).permit(:name,:price, :size))
		if @fry.save
			redirect_to :fries
		else
			render 'new'
		end
	end

	def destroy
		@fry = Fry.find(params[:id])
		@fry.destroy
		redirect_to :fries
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/fries_helper.rb
module FriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
Hi
<%= @articles.each do |a| %>
	<!-- <p><%= a.name %></p> -->
<% end %>

app/views/articles/new.html.erb
<%= form_with scope: :article, local: true do |form| %>

	<%= form.text_field :name,  placeholder: "Name", required: true %>

	<%= form.number_field :price, placeholder: "price in $", required: true %>

	<%= form.submit %>


<% end %>

app/views/burgers/index.html.erb
<h1>Burger List</h1>


<uL>
	<% @burgers.each do |b| %>
		<li><%= link_to(b.name, burger_path(b)) %> <%= b.type %></li>
	<% end %>
</uL>

app/views/burgers/new.html.erb
<%= form_with scope: :burger, url: burgers_path, local: true do |form| %>

	<%= form.text_field :name, :placeholder=> "Burger name" %><br>

	<%= form.number_field :price, :step=> 0.01, :min=>0, :placeholder=>"Price"%> $<br> 

	<%= form.text_area :description, :placeholder=>"Burger description" %><br>

	<%= form.submit %>

<% end %>

app/views/burgers/show.html.erb
<article>
	<h3><%= @burger.name %></h3>
	<em><%= @burger.price %> €</em>
	<p><%= @burger.description %></p>

	<%= button_to(name="Delete this burger", options={:controller => :burgers, :action=>:destroy, :id=>@burger.id}, html_options={:method=>:delete}) %>
</article>

app/views/desserts/index.html.erb
<h1>Desserts</h1>

<ul>
	<% @desserts.each do |d| %>
		<li><%= d.name + " " + d.price.to_s %></li>
	<% end %>
</ul>

app/views/desserts/new.html.erb
<%= form_with scope: @dessert,url: desserts_path, local: true do |form| %>

	<%= form.text_field :name, placeholder: "Name", required: true %>

	<%= form.number_field :price, :step=>0.01, :min=>0, required: true %>

	<%= form.submit %>

<% end %>

app/views/desserts/show.html.erb
<div>
	<h3><%= @dessert.name %></h3>
	<p><%= @dessert.price %></p>
</div>

app/views/drinks/index.html.erb
<% @drinks.each do |d| %>
	<p><%= link_to(d.name, options={:id=>d.id,:action=>:show}) %> <%= d.quantity %><%= d.unit %></p>
<% end %>

app/views/drinks/new.html.erb
<%= form_with scope: :drink, local: true, url: drinks_path do |f| %>

	<%= f.text_field :name, :placeholder=> :name , required: true %>

	<br>

	<%= f.number_field :quantity, :placeholder=> :quantity, required: true, step: 0.5, min: 0 %>

	<%= f.text_field :unit, :placeholder=> :cl, required: true %> 

	<br>

	<%= f.number_field :price, :placeholder => :price, required: true %> $

	<br>

	<%= f.submit %>

<% end %> 

app/views/drinks/show.html.erb
<p><%= @drink.name %> <strong><%= @drink.quantity %><%= @drink.unit %></strong> : <%= @drink.price %></p>

<%= button_to("Delete this drink !", options= {:controller=>:drinks, :action=>:destroy, :id=>@drink.id}, html_options= {:method=>:delete}) %>

app/views/fries/index.html.erb
<h2>Fries</h2>

<ul>
	<% @fries.each do |f| %>
		<li><%= link_to(f.name, fry_path(f)) %> <%= f.size %> <%= f.price %></li>
	<% end %>
</ul>

app/views/fries/new.html.erb
<%= form_with scope: :fry, url: fries_path, local: true do |form| %>

	<%= form.text_field :name, placeholder: "Name", required: true %>

	<%= form.number_field :price, placeholder: "Price", required: true %>

	<%= form.select :size, :collection => Fry.sizes.map { |key, value| [key.humanize, key] } %>

	<%= form.submit %>

<% end %>

app/views/fries/show.html.erb
<h1><%= @fry.name %></h1>

<p><%= @fry.name %> <%= @fry.size %> <%= @fry.price %></p>

<%= button_to(name="Delete this fry",options={:controller=>:fries,:action=>:destroy, :id=>@fry.id}, html_options={:method=>:delete}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BurgerShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome Customer</h1>